"""
build_data_js.py

Reads the source-of-truth dataset (data/technologies.json), runs a few
sanity checks with pandas, and compiles it into assets/data.js so the
front end can use it without needing a server or build step.

Run from the project root:
    python scripts/build_data_js.py
"""

import json
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
SOURCE_PATH = ROOT / "data" / "technologies.json"
OUTPUT_PATH = ROOT / "assets" / "data.js"

REQUIRED_FIELDS = [
    "id", "name", "category", "gravimetric_wt_pct", "volumetric_kg_per_m3",
    "trl", "cost_tier", "source",
]


def load_dataset(path: Path) -> dict:
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def validate(df: pd.DataFrame) -> None:
    """Lightweight data-quality checks. Raises if something looks wrong."""
    missing_cols = [c for c in REQUIRED_FIELDS if c not in df.columns]
    if missing_cols:
        raise ValueError(f"Dataset is missing required columns: {missing_cols}")

    if df["id"].duplicated().any():
        dupes = df.loc[df["id"].duplicated(), "id"].tolist()
        raise ValueError(f"Duplicate technology ids found: {dupes}")

    if (df["trl"].dropna() < 1).any() or (df["trl"].dropna() > 9).any():
        raise ValueError("TRL values must be between 1 and 9.")

    # Gravimetric capacity above ~20 wt% would be physically implausible
    # for any of the technologies covered here.
    bad_grav = df.loc[df["gravimetric_wt_pct"] > 20, "id"].tolist()
    if bad_grav:
        raise ValueError(f"Implausible gravimetric value for: {bad_grav}")

    print(f"Validated {len(df)} technology records.")


def main() -> None:
    dataset = load_dataset(SOURCE_PATH)
    df = pd.DataFrame(dataset["technologies"])
    validate(df)

    # Quick console summary, useful when re-running after editing the data.
    summary = (
        df.groupby("category")[["gravimetric_wt_pct", "volumetric_kg_per_m3"]]
        .mean(numeric_only=True)
        .round(1)
    )
    print("\nAverage capacity by category:")
    print(summary)

    js_content = (
        "// Auto-generated by scripts/build_data_js.py - do not edit by hand.\n"
        "// Source of truth: data/technologies.json\n"
        f"const H2_TECHNOLOGIES = {json.dumps(dataset['technologies'], indent=2)};\n"
        f"const H2_REFERENCE_TARGETS = {json.dumps(dataset['reference_targets'], indent=2)};\n"
        f"const H2_DATASET_META = {json.dumps(dataset['meta'], indent=2)};\n"
    )

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(js_content, encoding="utf-8")
    print(f"\nWrote {OUTPUT_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
